# Generated by Django 4.1.6 on 2023-02-18 23:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_ingrediente', models.CharField(choices=[('CRN', 'Carnes'), ('VRD', 'Verduras'), ('ESP', 'Especias'), ('LAC', 'Lacteos'), ('OVO', 'Huevos'), ('FRU', 'Frutas'), ('OTR', 'Otros')], default='OTR', max_length=3)),
                ('tipo_unidad', models.CharField(choices=[('PEN', 'Soles'), ('KG', 'Kilos'), ('LT', 'Litros'), ('GR', 'Gramos'), ('DOC', 'Docena(s)'), ('UN', 'Unidad(es)')], default='UN', max_length=3)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='M2M_Recetario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recetas_compras.ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ingr_principal', models.CharField(choices=[('AVE', 'Aves'), ('RES', 'Res'), ('CER', 'Cerdo'), ('MAR', 'Marino'), ('OVO', 'Huevos'), ('CON', 'Conservas'), ('OTR', 'Otros')], max_length=3)),
                ('image', models.ImageField(upload_to='recetas_compras/photos')),
                ('preparacion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('ingredientes', models.ManyToManyField(related_name='get_ingredientes', through='recetas_compras.M2M_Recetario', to='recetas_compras.ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('recetas', models.ManyToManyField(related_name='get_recetas', to='recetas_compras.receta')),
            ],
        ),
        migrations.AddField(
            model_name='m2m_recetario',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas_compras.receta'),
        ),
    ]
