# Generated by Django 4.1.6 on 2023-02-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='tipo_ingrediente',
            field=models.CharField(choices=[('CRN', 'Carnes'), ('VRD', 'Verduras'), ('ESP', 'Especias'), ('LAC', 'Lacteos'), ('OVO', 'Huevos'), ('FRU', 'Frutas'), ('GRA', 'Granos,Cereales'), ('OTR', 'Otros')], default='OTR', max_length=3),
        ),
    ]
