# Generated by Django 4.1.6 on 2023-02-20 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_compras', '0002_alter_ingrediente_tipo_ingrediente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='M2M_Recetario',
            new_name='M2MRecetario',
        ),
    ]
