# Generated by Django 4.1.6 on 2023-02-25 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_compras', '0003_rename_m2m_recetario_m2mrecetario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='m2mrecetario',
            unique_together={('ingrediente', 'receta')},
        ),
    ]
