# Generated by Django 4.1.6 on 2023-02-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_compras', '0004_alter_m2mrecetario_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='image',
            field=models.ImageField(blank=True, upload_to='recetas_compras/photos'),
        ),
    ]
