# Generated by Django 4.1.6 on 2023-03-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_compras', '0005_alter_receta_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='image',
            field=models.ImageField(blank=True, default='recetas_compras/photos/Image_not_available.png', upload_to='recetas_compras/photos'),
        ),
    ]
